env:
  gh_mail: "ENCRYPTED[a6555930826e36d6b1af8019b5a2f284e922b8c59ac7c098663ae1aaf0e48a3c3ae1ce2ad2794dbfb1d17bc161c202b5]"
  gh_username: "ENCRYPTED[e5724805479cf63e3efb55aac30e29523061a2746676e682b7a9a57e73c755aeefc5213d3981037700848ad3adac7eb5]"
  gh_token: "ENCRYPTED[1f997a2b01f020220f6d030da361da3262c47ae45acd0b58992338eca559362e5c86b076880f32731dcbfeac7f28e0c8]"

task:
  name: "Fuck Builder"
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Sync_script:
      - git config --global user.email "$gh_mail"
      - git config --global user.name "$gh_username"
      - git config --global credential.helper store
      - echo "https://$gh_username:$github_token@github.com" > ~/.git-credentials
      - echo "============================"
      - echo "   Syncing The Sources...   "
      - echo "============================"
      - cd ~
      - mkdir rom
      - cd rom
      - repo init --depth=1 --no-repo-verify -u https://github.com/Project-Elixir/official_manifest -b Tiramisu -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/$gh_username/local_manifest_vince --depth 1 -b elixir-12-private .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - echo "==========================="
      - echo "     Syncing Complete!    "
      - echo "==========================="

  Build_script:
      - echo "==========================="
      - echo "   Starting the Build...   "
      - echo "==========================="
      - cd ~
      - cd rom
      - source build/envsetup.sh
      - lunch aosp_vince-userdebug
      - export SELINUX_IGNORE_NEVERALLOWS=true
      - mka sepolicy
      - mka bootimage
      - mka init
